export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS";
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";

export const ADD_REVIEW = "ADD_REVIEW";
export const UPDATE_REVIEWS = "UPDATE_REVIEWS";
export const REMOVE_REVIEW = "REMOVE_REVIEW";

export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_MULTIPLE_TO_CART = "ADD_MULTIPLE_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";
export const TOGGLE_CART = "TOGGLE_CART";

export const UPDATE_CATEGORIES = "UPDATE_CATEGORIES";
export const UPDATE_CURRENT_CATEGORY = "UPDATE_CURRENT_CATEGORY";


export const GO_TO_COUPON = "GO_TO_COUPON"
export const GO_TO_ = "GO_TO_COUPON"







